apiVersion: v1
kind: Service
metadata:
  name: text-to-speech-frontend-service
  labels:
    app: text-to-speech-frontend
spec:
  selector:
    app: text-to-speech-frontend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Container port (Nginx listens on 80)
  type: ClusterIP # Use ClusterIP for internal access, an Ingress would typically expose it externally
